In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../election_resources/presidential_polls_2016.csv')
df= pd.DataFrame(data)
df.head()

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
0,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/1/16,U.S.,10/25/2016,10/31/2016,Google Consumer Surveys,B,...,42.64140,40.86509,5.675099,NaN,NaN,https://datastudio.google.com/u/0/#/org//repor...,47940,74999,11/1/16,15:09:38 1 Nov 2016
1,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/1/16,U.S.,10/27/2016,10/30/2016,ABC News/Washington Post,A+,...,43.29659,44.72984,3.401513,NaN,NaN,http://www.langerresearch.com/wp-content/uploa...,47881,74936,11/1/16,15:09:38 1 Nov 2016
2,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/1/16,Virginia,10/27/2016,10/30/2016,ABC News/Washington Post,A+,...,46.29779,40.72604,6.401513,NaN,NaN,https://www.washingtonpost.com/local/virginia-...,47880,74934,11/1/16,15:09:38 1 Nov 2016
3,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/1/16,Florida,10/20/2016,10/24/2016,SurveyUSA,A,...,46.35931,45.30585,1.777730,NaN,NaN,http://www.baynews9.com/content/news/baynews9/...,47465,74252,10/25/16,15:09:38 1 Nov 2016
4,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/1/16,U.S.,10/20/2016,10/25/2016,Pew Research Center,B+,...,45.32744,42.20888,3.618320,NaN,NaN,http://www.people-press.org/2016/10/27/as-elec...,47616,74519,10/27/16,15:09:38 1 Nov 2016

In [3]:
df['state'].value_counts()

U.S.                    3105
Florida                  360
North Carolina           303
Pennsylvania             285
Ohio                     273
New Hampshire            246
Virginia                 213
Nevada                   207
Wisconsin                189
Michigan                 189
Georgia                  183
Arizona                  180
Colorado                 174
Iowa                     168
California               165
Missouri                 153
New York                 150
Utah                     150
Illinois                 147
Texas                    135
Maine                    129
Indiana                  129
New Jersey               126
Oregon                   123
Massachusetts            117
South Carolina           117
Louisiana                117
Kansas                   117
Washington               114
Idaho                    114
Minnesota                111
Kentucky                 111
New Mexico               108
Maryland                 108
West Virginia            108
Tennessee                105
Arkansas                 102
Oklahoma                 102
Connecticut               99
Mississippi               96
Alabama                   96
Nebraska                  93
Montana                   93
Delaware                  90
Alaska                    87
South Dakota              81
Vermont                   78
North Dakota              66
Rhode Island              63
Wyoming                   63
Hawaii                    57
District of Columbia      54
Maine CD-2                42
Maine CD-1                33
Nebraska CD-2              6
Nebraska CD-1              3
Nebraska CD-3              3
Name: state, dtype: int64

In [4]:
new_df = df.loc[df['state'] == 'U.S.'] 
new_df.head()

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
0,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/1/16,U.S.,10/25/2016,10/31/2016,Google Consumer Surveys,B,...,42.64140,40.86509,5.675099,NaN,NaN,https://datastudio.google.com/u/0/#/org//repor...,47940,74999,11/1/16,15:09:38 1 Nov 2016
1,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/1/16,U.S.,10/27/2016,10/30/2016,ABC News/Washington Post,A+,...,43.29659,44.72984,3.401513,NaN,NaN,http://www.langerresearch.com/wp-content/uploa...,47881,74936,11/1/16,15:09:38 1 Nov 2016
4,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/1/16,U.S.,10/20/2016,10/25/2016,Pew Research Center,B+,...,45.32744,42.20888,3.618320,NaN,NaN,http://www.people-press.org/2016/10/27/as-elec...,47616,74519,10/27/16,15:09:38 1 Nov 2016
5,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/1/16,U.S.,10/22/2016,10/25/2016,Fox News/Anderson Robbins Research/Shaw & Comp...,A,...,44.65080,42.26663,6.114222,NaN,NaN,http://www.foxnews.com/politics/interactive/20...,47542,74365,10/26/16,15:09:38 1 Nov 2016
6,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/1/16,U.S.,10/26/2016,10/31/2016,IBD/TIPP,A-,...,46.21834,43.56017,3.153590,NaN,NaN,http://www.investors.com/politics/ibd-tipp-pre...,47875,74925,11/1/16,15:09:38 1 Nov 2016

In [5]:
new_df['state'].value_counts()

U.S.    3105
Name: state, dtype: int64

In [6]:
columns_to_drop =['pollster', 'grade', 'rawpoll_clinton', 'rawpoll_trump', 'rawpoll_johnson', 'rawpoll_mcmullin', 'url', 'question_id', 'createddate', 'timestamp', 'cycle', 
                  'branch', 'type', 'matchup', 'forecastdate', 'state', 'startdate', 'pollster', 'grade', 'adjpoll_johnson', 'adjpoll_mcmullin', 'multiversions', 'poll_id', 'population', 'poll_wt']
df = new_df.drop(columns=columns_to_drop)

In [7]:
df.head()

      enddate  samplesize  adjpoll_clinton  adjpoll_trump
0  10/31/2016     24316.0         42.64140       40.86509
1  10/30/2016      1128.0         43.29659       44.72984
4  10/25/2016      2120.0         45.32744       42.20888
5  10/25/2016      1221.0         44.65080       42.26663
6  10/31/2016      1018.0         46.21834       43.56017

In [8]:
r = df.copy()
d = df.copy()

In [9]:
r['party'] = 'r'
d['party'] = 'd'

In [10]:
r['favorability'] = r['adjpoll_trump']
d['favorability'] = d['adjpoll_clinton']
r = r.drop(columns=['adjpoll_clinton', 'adjpoll_trump'])
d = d.drop(columns=['adjpoll_trump', 'adjpoll_clinton'])

In [11]:
r.head()

      enddate  samplesize party  favorability
0  10/31/2016     24316.0     r      40.86509
1  10/30/2016      1128.0     r      44.72984
4  10/25/2016      2120.0     r      42.20888
5  10/25/2016      1221.0     r      42.26663
6  10/31/2016      1018.0     r      43.56017

In [12]:
rd2_df = pd.concat([r, d], ignore_index=True)
rd2_df.head()

      enddate  samplesize party  favorability
0  10/31/2016     24316.0     r      40.86509
1  10/30/2016      1128.0     r      44.72984
2  10/25/2016      2120.0     r      42.20888
3  10/25/2016      1221.0     r      42.26663
4  10/31/2016      1018.0     r      43.56017

In [13]:
rd2_df.tail()

         enddate  samplesize party  favorability
6205    1/1/2016       250.0     d      35.93998
6206  12/17/2015       289.0     d      41.02875
6207  11/16/2015      2001.0     d      45.01414
6208    8/2/2016       912.0     d      47.26828
6209    8/1/2016       490.0     d      47.30371

In [14]:
rd2_df['favorability'] = rd2_df['favorability'] - 50

In [15]:
rd2_df.drop(columns=['enddate'], inplace=True)

In [16]:
rd2_df.head()

   samplesize party  favorability
0     24316.0     r      -9.13491
1      1128.0     r      -5.27016
2      2120.0     r      -7.79112
3      1221.0     r      -7.73337
4      1018.0     r      -6.43983

In [17]:
results = {'d': 0, 'r': 1}
rd2_df['results'] = rd2_df['party'].apply(lambda x: results.get(x))
rd2_df.head()

   samplesize party  favorability  results
0     24316.0     r      -9.13491        1
1      1128.0     r      -5.27016        1
2      2120.0     r      -7.79112        1
3      1221.0     r      -7.73337        1
4      1018.0     r      -6.43983        1

In [18]:
rd2_df.shape

(6210, 4)

In [21]:
rd2_df.to_csv('../election_resources/cleaned_presidential_polls_2016.csv', index=False)