In [1]:
import pandas as pd

In [2]:
polling_df = pd.read_csv('../election_resources/favorability_polls_rv_2019.csv')
polling_df.head()

,question_id,start_date,end_date,pollster_id,pollster,sponsors,sample_size,population,methodology,url,politician,favorable,unfavorable,very_favorable,somewhat_favorable,somewhat_unfavorable,very_unfavorable
0,114577,12/7/2019,12/10/2019,568,YouGov,Economist,1195,rv,Online,https://d25d2506sfb94s.cloudfront.net/cumulus_...,Michael F. Bennet,14.0,29.0,4.0,10.0,12.0,17.0
1,114585,12/7/2019,12/10/2019,568,YouGov,Economist,1198,rv,Online,https://d25d2506sfb94s.cloudfront.net/cumulus_...,Michael Bloomberg,24.0,58.0,7.0,17.0,20.0,38.0
2,114589,12/7/2019,12/10/2019,568,YouGov,Economist,1198,rv,Online,https://d25d2506sfb94s.cloudfront.net/cumulus_...,Cory A. Booker,35.0,45.0,11.0,24.0,12.0,33.0
3,114593,12/7/2019,12/10/2019,568,YouGov,Economist,1198,rv,Online,https://d25d2506sfb94s.cloudfront.net/cumulus_...,Steve Bullock,14.0,27.0,3.0,11.0,11.0,16.0
4,114597,12/7/2019,12/10/2019,568,YouGov,Economist,1202,rv,Online,https://d25d2506sfb94s.cloudfront.net/cumulus_...,Pete Buttigieg,35.0,44.0,14.0,21.0,13.0,31.0

In [3]:
polling_df.describe()

,question_id,pollster_id,sample_size,favorable,unfavorable,very_favorable,somewhat_favorable,somewhat_unfavorable,very_unfavorable
count,1631.000000,1631.000000,1631.000000,1631.000000,1631.000000,1390.000000,1390.000000,1390.000000,1389.000000
mean,101904.902514,836.244635,1263.738197,27.369651,32.833476,10.675396,16.431007,10.995036,21.735277
std,6561.371161,390.365914,347.533032,12.322381,12.386363,7.821444,5.910113,3.502219,10.351611
min,94880.000000,11.000000,442.000000,2.000000,6.000000,1.000000,4.000000,4.000000,4.000000
25%,96842.500000,568.000000,1072.500000,17.000000,22.000000,5.000000,12.000000,8.000000,13.000000
50%,99386.000000,568.000000,1181.000000,27.000000,33.000000,8.000000,17.000000,11.000000,20.000000
75%,104004.000000,1189.000000,1268.000000,38.000000,42.000000,16.000000,21.000000,13.000000,29.000000
max,114836.000000,1508.000000,2531.000000,56.000000,58.000000,35.000000,33.000000,48.000000,52.000000