In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

c:\Users\Nomanos\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

## Import data and create data frames

In [2]:
state_gun_laws_df = pd.read_csv('../Resources/Crime_Data/state_gun_law_state.csv')
state_gun_laws_df.head(30)

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,expartedating,dvrosurrender,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal
0,AL,1991,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,15
1,AL,1992,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
2,AL,1993,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
3,AL,1994,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
4,AL,1995,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
5,AL,1996,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
6,AL,1997,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
7,AL,1998,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
8,AL,1999,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
9,AL,2000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
10,AL,2001,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
11,AL,2002,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
12,AL,2003,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
13,AL,2004,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
14,AL,2005,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
15,AL,2006,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
16,AL,2007,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
17,AL,2008,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
18,AL,2009,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
19,AL,2010,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
20,AL,2011,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
21,AL,2012,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
22,AL,2013,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
23,AL,2014,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
24,AL,2015,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
25,AL,2016,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
26,AL,2017,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
27,AL,2018,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
28,AL,2019,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
29,AL,2020,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10

In [3]:
cdc_death_rate_df= pd.read_csv('../Resources/Crime_Data/CDC_death_rate_state20.csv')
cdc_death_rate_df.head()

   YEAR STATE  RATE  DEATHS                                       URL
0  2021    AL  26.4    1315     /nchs/pressroom/states/alabama/al.htm
1  2021    AK  25.2     182      /nchs/pressroom/states/alaska/ak.htm
2  2021    AZ  18.3    1365     /nchs/pressroom/states/arizona/az.htm
3  2021    AR  23.3     698    /nchs/pressroom/states/arkansas/ar.htm
4  2021    CA   9.0    3576  /nchs/pressroom/states/california/ca.htm

In [4]:
cdc_death_rate_df = cdc_death_rate_df.drop(columns=['URL'])

In [5]:
cdc_death_rate_df

     YEAR STATE  RATE  DEATHS
0    2021    AL  26.4    1315
1    2021    AK  25.2     182
2    2021    AZ  18.3    1365
3    2021    AR  23.3     698
4    2021    CA   9.0    3576
..    ...   ...   ...     ...
445  2005    VA  11.5     888
446  2005    WA   8.8     567
447  2005    WV  13.8     261
448  2005    WI   8.5     474
449  2005    WY  13.4      71

[450 rows x 4 columns]

In [6]:
state_law_and_death_rate=state_gun_laws_df.merge(cdc_death_rate_df, left_on=['state', 'year'], right_on=['STATE', 'YEAR'], how='left')
state_law_and_death_rate

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,YEAR,STATE,RATE,DEATHS
0,AL,1991,0,0,0,0,0,0,1,0,...,0,0,0,0,0,15,NaN,NaN,NaN,NaN
1,AL,1992,0,0,0,0,0,0,1,0,...,0,0,0,0,1,16,NaN,NaN,NaN,NaN
2,AL,1993,0,0,0,0,0,0,1,0,...,0,0,0,0,1,16,NaN,NaN,NaN,NaN
3,AL,1994,0,0,0,0,0,0,1,0,...,0,0,0,0,1,16,NaN,NaN,NaN,NaN
4,AL,1995,0,0,0,0,0,0,1,0,...,0,0,0,0,1,16,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,WY,2016,1,0,0,0,0,0,0,0,...,0,0,0,0,0,8,2016.0,WY,17.4,101.0
1496,WY,2017,1,0,0,0,0,0,0,0,...,0,0,0,0,0,8,2017.0,WY,18.8,113.0
1497,WY,2018,1,0,0,0,0,0,0,0,...,0,0,0,0,0,7,2018.0,WY,21.5,124.0
1498,WY,2019,1,0,0,0,0,0,0,0,...,0,0,0,0,0,7,2019.0,WY,22.3,133.0
1499,WY,2020,1,0,0,0,0,0,0,0,...,0,0,0,0,0,7,2020.0,WY,25.9,154.0

In [7]:
state_law_and_death_rate=state_law_and_death_rate.dropna()
state_law_and_death_rate

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,YEAR,STATE,RATE,DEATHS
14,AL,2005,0,0,0,0,0,0,1,0,...,0,0,0,0,1,11,2005.0,AL,16.0,736.0
23,AL,2014,0,0,0,0,0,0,1,0,...,0,0,0,0,0,10,2014.0,AL,16.9,815.0
24,AL,2015,0,1,0,1,0,0,1,0,...,0,0,0,0,0,10,2015.0,AL,19.6,958.0
25,AL,2016,0,1,0,1,0,0,1,0,...,0,0,0,0,0,10,2016.0,AL,21.5,1046.0
26,AL,2017,0,1,0,1,0,0,1,0,...,0,0,0,0,0,10,2017.0,AL,22.9,1124.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,WY,2016,1,0,0,0,0,0,0,0,...,0,0,0,0,0,8,2016.0,WY,17.4,101.0
1496,WY,2017,1,0,0,0,0,0,0,0,...,0,0,0,0,0,8,2017.0,WY,18.8,113.0
1497,WY,2018,1,0,0,0,0,0,0,0,...,0,0,0,0,0,7,2018.0,WY,21.5,124.0
1498,WY,2019,1,0,0,0,0,0,0,0,...,0,0,0,0,0,7,2019.0,WY,22.3,133.0
1499,WY,2020,1,0,0,0,0,0,0,0,...,0,0,0,0,0,7,2020.0,WY,25.9,154.0

In [8]:
clean_statelaw_deathrate_df= state_law_and_death_rate.drop(columns=["STATE","YEAR"])
clean_statelaw_deathrate_df

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,RATE,DEATHS
14,AL,2005,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,11,16.0,736.0
23,AL,2014,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,10,16.9,815.0
24,AL,2015,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,10,19.6,958.0
25,AL,2016,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,10,21.5,1046.0
26,AL,2017,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,10,22.9,1124.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,WY,2016,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,8,17.4,101.0
1496,WY,2017,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,8,18.8,113.0
1497,WY,2018,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,21.5,124.0
1498,WY,2019,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,22.3,133.0
1499,WY,2020,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,25.9,154.0

In [9]:
clean_statelaw_deathrate_df.rename(columns={"RATE": "Rate_in_100k", "DEATHS": "Total_Deaths"}, inplace=True)
clean_statelaw_deathrate_df

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,Rate_in_100k,Total_Deaths
14,AL,2005,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,11,16.0,736.0
23,AL,2014,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,10,16.9,815.0
24,AL,2015,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,10,19.6,958.0
25,AL,2016,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,10,21.5,1046.0
26,AL,2017,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,10,22.9,1124.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,WY,2016,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,8,17.4,101.0
1496,WY,2017,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,8,18.8,113.0
1497,WY,2018,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,21.5,124.0
1498,WY,2019,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,22.3,133.0
1499,WY,2020,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,25.9,154.0

In [10]:
clean_statelaw_deathrate_df.to_csv('../Resources/Crime_Data/state_gun_and_deathrate.csv', index=False)