In [1]:
import pandas as pd
import numpy as np

In [2]:
state_gun_laws_df = pd.read_csv('../Resources/Laws/state_gun_laws.csv')

In [3]:
state_gun_laws_df.head(50)

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,expartedating,dvrosurrender,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal
0,Alabama,1991,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,15
1,Alabama,1992,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
2,Alabama,1993,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
3,Alabama,1994,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
4,Alabama,1995,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
5,Alabama,1996,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
6,Alabama,1997,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
7,Alabama,1998,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
8,Alabama,1999,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
9,Alabama,2000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
10,Alabama,2001,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
11,Alabama,2002,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
12,Alabama,2003,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
13,Alabama,2004,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
14,Alabama,2005,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
15,Alabama,2006,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
16,Alabama,2007,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
17,Alabama,2008,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
18,Alabama,2009,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
19,Alabama,2010,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
20,Alabama,2011,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
21,Alabama,2012,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
22,Alabama,2013,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
23,Alabama,2014,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
24,Alabama,2015,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
25,Alabama,2016,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
26,Alabama,2017,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
27,Alabama,2018,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
28,Alabama,2019,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
29,Alabama,2020,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,10
30,Alaska,1991,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
31,Alaska,1992,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,11
32,Alaska,1993,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,11
33,Alaska,1994,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
34,Alaska,1995,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
35,Alaska,1996,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
36,Alaska,1997,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
37,Alaska,1998,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
38,Alaska,1999,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
39,Alaska,2000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
40,Alaska,2001,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
41,Alaska,2002,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
42,Alaska,2003,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
43,Alaska,2004,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
44,Alaska,2005,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
45,Alaska,2006,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
46,Alaska,2007,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
47,Alaska,2008,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
48,Alaska,2009,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
49,Alaska,2010,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4

In [4]:
state_abbreviations= {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}

In [5]:
state_gun_laws_df['state']= state_gun_laws_df['state'].replace(state_abbreviations)

In [10]:
state_gun_laws_df.head(20)

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,expartedating,dvrosurrender,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal
0,AL,1991,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,15
1,AL,1992,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
2,AL,1993,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
3,AL,1994,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
4,AL,1995,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
5,AL,1996,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
6,AL,1997,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
7,AL,1998,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
8,AL,1999,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
9,AL,2000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
10,AL,2001,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
11,AL,2002,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
12,AL,2003,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
13,AL,2004,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
14,AL,2005,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
15,AL,2006,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
16,AL,2007,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
17,AL,2008,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
18,AL,2009,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11
19,AL,2010,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,11

In [13]:
state_gun_laws_df1=state_gun_laws_df.copy()
state_gun_laws_df1.columns

Index(['state', 'year', 'felony', 'invcommitment', 'invoutpatient', 'danger',
       'drugmisdemeanor', 'alctreatment', 'alcoholism', 'relinquishment',
       ...
       'expartedating', 'dvrosurrender', 'dvrosurrendernoconditions',
       'dvrosurrenderdating', 'expartesurrender',
       'expartesurrendernoconditions', 'expartesurrenderdating', 'dvroremoval',
       'stalking', 'lawtotal'],
      dtype='object', length=137)

In [15]:
state_gun_laws_red= state_gun_laws_df1.loc[:,['state', 'year', 'lawtotal']]
state_gun_laws_red

     state  year  lawtotal
0       AL  1991        15
1       AL  1992        16
2       AL  1993        16
3       AL  1994        16
4       AL  1995        16
...    ...   ...       ...
1495    WY  2016         8
1496    WY  2017         8
1497    WY  2018         7
1498    WY  2019         7
1499    WY  2020         7

[1500 rows x 3 columns]

In [18]:
national_crime_df = pd.read_csv('../Resources/Crime_Data/national_crime_by_year.csv')

In [20]:
national_crime_df.head()

   data_year State  Total_Shootings
0       1991    AL             9688
1       1991    IL                6
2       1991    ND               22
3       1991    SC            11434
4       1992    AL             8553

In [25]:
national_crime_grouped_df= national_crime_df.sort_values(by=['data_year','State'])

In [29]:
national_crime_grouped_df

     data_year State  Total_Shootings
0         1991    AL             9688
1         1991    IL                6
2         1991    ND               22
3         1991    SC            11434
4         1992    AL             8553
..         ...   ...              ...
884       2021    VT              206
885       2021    WA             9573
886       2021    WI            15548
887       2021    WV             2038
888       2021    WY              277

[889 rows x 3 columns]

In [30]:
state_laws_and_national_crime=state_gun_laws_df1.merge(national_crime_df, left_on=['state', 'year'], right_on=['State', 'data_year'], how='left')
#state_laws_and_national_crime.drop(['data_year', 'State'], axis=1, inplace=True)
state_laws_and_national_crime

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal,data_year,State,Total_Shootings
0,AL,1991,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,15,1991.0,AL,9688.0
1,AL,1992,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,16,1992.0,AL,8553.0
2,AL,1993,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,16,NaN,NaN,NaN
3,AL,1994,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,16,NaN,NaN,NaN
4,AL,1995,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,16,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,WY,2016,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,8,NaN,NaN,NaN
1496,WY,2017,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,8,NaN,NaN,NaN
1497,WY,2018,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,7,NaN,NaN,NaN
1498,WY,2019,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,7,2019.0,WY,20.0
1499,WY,2020,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,7,2020.0,WY,33.0

In [31]:
state_laws_and_national_crime.to_csv('../Resources/Crime_Data/state_gun_and_crime.csv', index=False)